### ISSUE TITLE
version 1.0 not working 

### ISSUE THREAD

**Issue by henkied** [Sunoo/homebridge-plugin-update-check#22]
after updating to version 1.0 plugin is not working:

Alpine Linux (3.12.9)
v16.13.1
v8.1.2

</div></div></app-system-info-widget></app-widgets></gridster-item>

[1/15/2022, 10:21:43 AM] ERROR LOADING PLUGIN homebridge-plugin-update-check:
[1/15/2022, 10:21:43 AM] Error: EACCES: permission denied, open '/root/.npmrc'
    at Object.openSync (node:fs:585:3)
    at Object.readFileSync (node:fs:453:35)
    at maybeReadIni (/homebridge/node_modules/homebridge-plugin-update-check/node_modules/libnpmconfig/index.js:81:14)
    at Object.getNpmConfig [as read] (/homebridge/node_modules/homebridge-plugin-update-check/node_modules/libnpmconfig/index.js:43:32)
    at readNpmConfig (/homebridge/node_modules/homebridge-plugin-update-check/node_modules/npm-check-updates/src/package-managers/npm.ts:47:16)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-update-check/node_modules/npm-check-updates/src/package-managers/npm.ts:74:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
[1/15/2022, 10:21:43 AM] ====================

[1/15/2022, 10:21:44 AM] No plugin was found for the platform "PluginUpdate" in your config.json. Please make sure the corresponding plugin is installed correctly.

config:

 {
            "name": "Plugin Update",
            "sensorType": "motion",
            "platform": "PluginUpdate"

**Comment by Sunoo** [comment]
I see you’re using Alpine, I assume this is under Docker then?

**Comment by Sunoo** [comment]
Also, what version of NodeJS are you running?

**Comment by henkied** [comment]
> I see you’re using Alpine, I assume this is under Docker then?

Yes under docker on synology nas

**Comment by henkied** [comment]
> Also, what version of NodeJS are you running?

/homebridge # node -v
v16.13.1

**Comment by Sunoo** [comment]
Okay, I don’t currently have a Docker environment set up. I’ll try to get one going shortly and see if I can recreate it.

**Comment by Sunoo** [comment]
This should be fixed in v1.0.1, sorry about that.

**Comment by henkied** [comment]
great it works thank you
